# 自封装应用库
MESSAGE (STATUS "comlib set begin")

## 设置自封装应用库的头文件
SET(COMM_INCLUDE            ${PROJECT_SOURCE_DIR}/include/comlib)

SET(STIBEL_COMMON_INCLUDE   ${COMM_INCLUDE}/StiBel/Common/include)
SET(STIBEL_MYSQL_INCLUDE    ${COMM_INCLUDE}/StiBel/Data/MySQL/include ${MYQSL_INCLUDE})
SET(STIBEL_REDIS_INCLUDE    ${COMM_INCLUDE}/StiBel/Data/Redis/include)
SET(STIBEL_LOG_INCLUDE      ${COMM_INCLUDE}/StiBel/Log/include)
SET(STIBEL_JSON_INCLUDE     ${COMM_INCLUDE}/StiBel/JSON/include)

## 自封装应用库的头文件集合
set(COMM_INCLUDE_PATH ${STIBEL_COMMON_INCLUDE} ${STIBEL_MYSQL_INCLUDE} ${STIBEL_REDIS_INCLUDE} 
${STIBEL_LOG_INCLUDE} ${STIBEL_JSON_INCLUDE})

MESSAGE (STATUS "COMM_INCLUDE_PATH:       " ${COMM_INCLUDE_PATH})

## 设置自封装应用库的链接名称，便于快速使用
SET(LIB_STIBEL_COMMON   StiBel_common_${LIB_VERSION} ${LIB_PTHREAD})
SET(LIB_STIBEL_MYSQL    StiBel_mysql_${LIB_VERSION}  ${LIB_MYSQL} )
SET(LIB_STIBEL_REDIS    StiBel_redis_${LIB_VERSION}  ${LIB_HIREDIS})
SET(LIB_STIBEL_LOG      StiBel_log_${LIB_VERSION}    ${LIB_LOG4CPP} ${LIB_PTHREAD} ${LIB_STIBEL_COMMON})
SET(LIB_STIBEL_JSON     StiBel_json_${LIB_VERSION}   ${LIB_JSONCPP})

## 自封装应用库名列表，便于快速使用
set(COMM_LIB_LIST ${LIB_STIBEL_COMMON} ${LIB_STIBEL_MYSQL} ${LIB_STIBEL_REDIS} 
${LIB_STIBEL_LOG} ${LIB_STIBEL_JSON})

MESSAGE (STATUS "COMM_LIB_LIST:       " ${COMM_LIB_LIST})

MESSAGE (STATUS "comlib set begin")