# 自封装应用库

## 设置自封装应用库的头文件
SET(COMM_INCLUDE            ${PROJECT_SOURCE_DIR}/include/comlib)

SET(STIBEL_COMMON_INCLUDE   ${COMM_INCLUDE}/StiBel/Common/include)
SET(STIBEL_MYSQL_INCLUDE    ${COMM_INCLUDE}/StiBel/Data/MySQL/include ${MYQSL_INCLUDE})
SET(STIBEL_REDIS_INCLUDE    ${COMM_INCLUDE}/StiBel/Data/Redis/include)
SET(STIBEL_LOG_INCLUDE      ${COMM_INCLUDE}/StiBel/Log/include)
SET(STIBEL_JSON_INCLUDE     ${COMM_INCLUDE}/StiBel/JSON/include)

## 设置自封装应用库的链接名称
SET(LIB_STIBEL_COMMON   StiBel_common_${LIB_VERSION} ${LIB_PTHREAD})
SET(LIB_STIBEL_MYSQL    StiBel_mysql_${LIB_VERSION}  ${LIB_MYSQL} )
SET(LIB_STIBEL_REDIS    StiBel_redis_${LIB_VERSION}  ${LIB_HIREDIS})
SET(LIB_STIBEL_LOG      StiBel_log_${LIB_VERSION}    ${LIB_LOG4CPP} ${LIB_PTHREAD} ${LIB_STIBEL_COMMON})
SET(LIB_STIBEL_JSON     StiBel_json_${LIB_VERSION}   ${LIB_JSONCPP})