# 获取当前编译的时间
STRING(TIMESTAMP COMPILE_TIME  "%Y-%m-%d %H:%M:%S [UTC]" UTC)

# PROJECT_BINARY_DIR：运行cmake命令的目录, PROJECT_SOURCE_DIR：工程根目录
MESSAGE (STATUS "PROJECT_BINARY_DIR:       " ${PROJECT_BINARY_DIR})
MESSAGE (STATUS "PROJECT_SOURCE_DIR:       " ${PROJECT_SOURCE_DIR})
MESSAGE (STATUS "BUILD_TYPE:               " ${BUILD_TYPE})
MESSAGE (STATUS "LIB_VERSION:              " ${LIB_VERSION})
MESSAGE (STATUS "COMPILE_TIME:             " ${COMPILE_TIME})
MESSAGE (STATUS "COMPILE_SYSTEM:           " ${CMAKE_SYSTEM_NAME})

MESSAGE (STATUS "CMAKE_CXX_FLAGS:               " ${CMAKE_CXX_FLAGS})
MESSAGE (STATUS "CMAKE_CXX_FLAGS_DEBUG:         " ${CMAKE_CXX_FLAGS_DEBUG})
MESSAGE (STATUS "CMAKE_CXX_FLAGS_RELEASE:       " ${CMAKE_CXX_FLAGS_RELEASE})

MESSAGE (STATUS "CMAKE_C_FLAGS:                 " ${CMAKE_C_FLAGS})
MESSAGE (STATUS "CMAKE_C_FLAGS_DEBUG:           " ${CMAKE_C_FLAGS_DEBUG})
MESSAGE (STATUS "CMAKE_C_FLAGS_RELEASE:         " ${CMAKE_C_FLAGS_RELEASE})